import sys, time, os
sys.path.append('/Users/Sorin/Issuu/new_eclipse_ws/frontend-issuu-autotest/autotest_framework/')

import SeleniumTestCase, make_platform_classes
import SetTestStatus as sts

import unittest, xmlrunner

class TestHowToPRO(SeleniumTestCase.SeleniumTestCase):
    
    def test_how_to(self):
        try:
            sel = self.selenium
            sel.set_speed("1000")
            sel.open("/business/howto")
            sel.wait_for_page_to_load("60000")
            #sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='Issuu PRO']")
            #sel.wait_for_page_to_load("60000")
            #sel.go_back()
            #sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='Features']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//span[.='Resellers']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//span[.='Pricing']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='FAQ']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='Cases']")
            sel.wait_for_page_to_load("60000")
            self.assertEqual("Issuu Pro - Cases", sel.get_title())
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='Sign up']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//div[@class='page-wrapper']//a[.='Sign up']")
            sel.wait_for_page_to_load("60000")
            self.assertEqual("Issuu Pro - How-to signup", sel.get_title())
            self.failUnless(sel.is_element_present("xpath=//div[@class='howtomaincornerB']/div/div/div/div"))
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Uploading")
            sel.wait_for_page_to_load("60000")
            self.failUnless(sel.is_element_present("xpath=//div[@class='howtomaincornerB']/div/div/div/div"))
            self.assertEqual("Issuu Pro - How-to upload", sel.get_title())
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Embedding a Mini-Issuu")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Embedding a Standalone Issuu")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Getting Issuu on Facebook profiles")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Statistics")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.click("link=Login")
            sel.wait_for_page_to_load("60000")
            sel.type("id=username", "PROaccount")
            sel.type("id=password", "autotest")
            sel.click("xpath=//span[@class='system-blue-shade-fat-btn-text']//strong[.='Log in']")
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='Issuu PRO']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='Features']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//span[.='Resellers']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//span[.='Pricing']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='FAQ']")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("xpath=//ul[@class='horizontal-listBiz']//strong[.='Cases']")
            sel.wait_for_page_to_load("60000")
            self.assertEqual("Issuu Pro - Cases", sel.get_title())
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Uploading")
            sel.wait_for_page_to_load("60000")
            self.failUnless(sel.is_element_present("xpath=//div[@class='howtomaincornerB']/div/div/div/div"))
            self.assertEqual("Issuu Pro - How-to upload", sel.get_title())
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Embedding a Mini-Issuu")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Embedding a Standalone Issuu")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Getting Issuu on Facebook profiles")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.wait_for_page_to_load("60000")
            sel.click("link=Statistics")
            sel.wait_for_page_to_load("60000")
            sel.go_back()
            sel.click("link=Logout")
            sel.wait_for_page_to_load("60000")
            
            #print self.__class__.__name__ + " passed!"
            #sts.set_test_status(self.selenium.get_eval("selenium.sessionId"), passed=True) 
            
        except AttributeError:
            pass
        #except: # catch *all* exceptions
            #if  sys.exc_info()[1]:
                #sts.set_test_status(self.selenium.get_eval("selenium.sessionId"), passed=False)
                #print self.__class__.__name__ + " failed!"
                
globals().update(make_platform_classes.make_platform_classes(TestHowToPRO))

if __name__ == '__main__':
    unittest.main(testRunner=xmlrunner.XMLTestRunner(output='../test_reports'))